### ISSUE TITLE
Packaging for app server with Java 11 is not described in readme

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/skeleton-starter-flow-spring#200]
Even that it's just using `java11` profile with maven while packaging, it's not documented in read me, and might be not obvious for everyone.

That is applied to most of the starters.

**Comment by joheriks** [comment]
What kind of documentation could we add? The `java11` profile should not be needed to be activated by the user, as it is there to add missing plugin dependencies for `maven-failsafe-plugin` and Selenium `driver-binary-downloader-maven-plugin` when running ITs under profile `integration-tests` (it is automatically activated when jdk 11 is detected).

**Comment by Skrikjo** [comment]
so is I build war with java 11 without `java11` profile and deploy it to tomcat that is running under java 11 everything should work without issues?

**Comment by joheriks** [comment]
The profile also sets `<maven.compiler.release>11</maven.compiler.release>`. Anyway, as the profile is activated automatically under the above premises, the answer to that question would be yes.

**Comment by Skrikjo** [comment]
Oh I guess it's my fault. Just checked it with java 11 it works fine. 
I guess it was build with java 12... so I got next exception:

```
23-Jul-2019 14:46:19.754 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ApplicationContext.log Servlet [springServlet] threw unload() exception
	javax.servlet.ServletException: Servlet.destroy() for servlet [springServlet] threw exception
		at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1310)
		at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1633)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5462)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
		at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:845)
		at org.apache.catalina.startup.HostConfig.undeploy(HostConfig.java:1427)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1354)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1613)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:314)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1170)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1364)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: java.lang.IllegalStateException: java.io.IOException: java.lang.reflect.InvocationTargetException
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:100)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:257)
		at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
		at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
		at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
		at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2285)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
		at org.atmosphere.cpr.AtmosphereFramework.destroy(AtmosphereFramework.java:1839)
		at com.vaadin.flow.server.communication.PushRequestHandler.destroy(PushRequestHandler.java:268)
		at com.vaadin.flow.server.communication.PushRequestHandler.lambda$new$31087998$1(PushRequestHandler.java:76)
		at com.vaadin.flow.server.VaadinService.lambda$destroy$8(VaadinService.java:2032)
		at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
		at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5534)
		at com.vaadin.flow.server.VaadinService.destroy(VaadinService.java:2032)
		at com.vaadin.flow.server.VaadinServlet.destroy(VaadinServlet.java:485)
		at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1299)
		... 15 more
	Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
		at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:212)
		at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:181)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:96)
		... 33 more
	Caused by: java.lang.reflect.InvocationTargetException
		at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
		at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
		... 36 more
	Caused by: java.nio.file.NoSuchFileException: /Users/vladyslavgutsul/soft/tomcat-8/webapps/sboot-v14rc6-1.0/WEB-INF/lib/jackson-databind-2.9.8.jar
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
		at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
		at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
		at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
		at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
		at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
		at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
		... 40 more
23-Jul-2019 14:46:19.756 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ApplicationContext.log Destroying Spring FrameworkServlet 'dispatcherServlet'
23-Jul-2019 14:46:19.773 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
23-Jul-2019 14:46:19.776 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.springframework.boot.web.servlet.support.SpringBootServletInitializer$1]
	java.lang.IllegalStateException: java.io.IOException: java.lang.reflect.InvocationTargetException
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:100)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:257)
		at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
		at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
		at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
		at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2285)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
		at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:113)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4815)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5474)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
		at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:845)
		at org.apache.catalina.startup.HostConfig.undeploy(HostConfig.java:1427)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1354)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1613)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:314)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1170)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1364)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
		at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:212)
		at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:181)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:96)
		... 24 more
	Caused by: java.lang.reflect.InvocationTargetException
		at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
		at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
		... 27 more
	Caused by: java.nio.file.NoSuchFileException: /Users/vladyslavgutsul/soft/tomcat-8/webapps/sboot-v14rc6-1.0/WEB-INF/lib/jackson-databind-2.9.8.jar
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
		at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
		at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
		at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
		at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
		at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
		at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
		... 31 more
23-Jul-2019 15:05:02.148 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
23-Jul-2019 15:05:03.544 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
23-Jul-2019 15:05:04.153 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Initializing AtmosphereFramework

```

will close the issue
