### ISSUE TITLE
Can't find resource ExamplteTemplate.html

### ISSUE THREAD

**Issue by Leaghte** [vaadin/skeleton-starter-flow-spring#28]
Hi, when i start `skeleton-starter-flow-spring` application with `mvn clean install spring-boot:run`, and then navigate to `localhost:8080` i got this exception :

> Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://ExampleTemplate.html' via the servlet context
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:106) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:122) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:62) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:72) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.starter.skeleton.spring.ExampleTemplate.<init>(ExampleTemplate.java:45) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]

I can see that file located in fronted folder correctly in META-INF/resources/fronted/

**Comment by SomeoneToIgnore** [comment]
Hi.

This is rather odd, just checked out `master` and run exactly the same command – works for me.
Is there a possibility that you've used the old version? We've updated the project yesterday.

**Comment by ahie** [comment]
Same as @SomeoneToIgnore. Tested on my machine on a fresh clone of the repo and it works as expected.

**Comment by Leaghte** [comment]
I've just did fresh clone of project from the master repository in both my laptop and desktop. But same result: `Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://ExampleTemplate.html' via the servlet context`
Any suggestions what is causing this error?

**Comment by SomeoneToIgnore** [comment]
Have checked it out on macOs, linux, windows 10 and even Ubuntu Docker image – still works.

You can check out the logs before the exception, there should be a log entry starting with `Html import path ...` that will show the resolution path.

If it won't be enough, you can debug the app, put a breakpoint somewhere in  `VaadinUriResolverFactory#toServletContextPath` method, this is the one that is responsible for paths resolutions.

**Comment by Legioth** [comment]
Two ideas about what could cause this problem in some cases but not in other:
* Whitespace or some other special characters in the name of some parent directory (potentially only on some operating systems).
* Different Java versions.

**Comment by Leaghte** [comment]
Thanks guys for your help. I really appreciate it.  At the end, the whitespace in the name of parent directory was the cause.

**Comment by Legioth** [comment]
I created https://github.com/vaadin/flow/issues/3262 in Flow for investigating the case with whitespace in directory names.
