### ISSUE TITLE
Auto-reload not working with Intellij IDEA

### ISSUE THREAD

**Issue by xylo** [vaadin/skeleton-starter-flow-spring#399]
Yesterday I've created a new vaadin 17 and pure Java project using your project configurator https://start.vaadin.com/?preset=latest.  Thereto I added the card list view, the master-detail view, and the form view.

Running `mvn spring-boot:run` on the downloaded project works fine.  The app can be used in the browser.

I also opened the project in Inteliij IDEA, renamed just a button and recompiled the project in IDEA by pressing on compile.  Spring boot detected the changes and reloaded the app.  However, instead of a working reload I get this:
![grafik](https://user-images.githubusercontent.com/577869/92572110-46768a00-f284-11ea-8a24-9e4faf5c5def.png)

And the log shows me
```
Vaadin application has been deployed and started to the context path "/".
2020-09-09 09:36:37.815  INFO 286042 --- [onPool-worker-3] c.v.f.s.f.TaskGeneratePackageJson        : writing file /home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/flow-frontend/package.json.
2020-09-09 09:36:37.817  INFO 286042 --- [onPool-worker-3] c.v.f.s.f.TaskGeneratePackageJson        : writing file /home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/flow-frontend/form/package.json.
2020-09-09 09:36:37.818  INFO 286042 --- [onPool-worker-3] c.v.f.s.frontend.TaskGenerateIndexHtml   : writing file '/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/index.html'
2020-09-09 09:36:37.819  INFO 286042 --- [onPool-worker-3] c.v.f.s.frontend.TaskGenerateIndexTs     : writing file '/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/index.ts'
2020-09-09 09:36:37.820  INFO 286042 --- [onPool-worker-3] c.v.f.s.c.g.OpenApiSpecGenerator         : Parsing java files from [/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/src/main/java]
ℹ ｢wdm｣: Compiling...
2020-09-09 09:36:37.887  WARN 286042 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Cannot deserialize session attribute [com.vaadin.flow.server.VaadinSession.springServlet] for session [1A2C3146B5935F7781FB16D9BF0BCDBB]
2020-09-09 09:36:37.905 ERROR 286042 --- [  restartedMain] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.io.InvalidClassException: [Ljava.lang.StackTraceElement;; no valid constructor
        at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:169) ~[na:1.8.0_181]
        at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:874) ~[na:1.8.0_181]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2043) ~[na:1.8.0_181]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[na:1.8.0_181]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[na:1.8.0_181]
        at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1545) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1040) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:218) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.session.StandardManager.load(StandardManager.java:162) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:354) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_181]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_181]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:437) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at iat.vaadin17.Application.main(Application.java:14) [classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.3.2.RELEASE.jar:2.3.2.RELEASE]

2020-09-09 09:36:37.945  INFO 286042 --- [  restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-09-09 09:36:37.954  INFO 286042 --- [         task-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-09-09 09:36:37.970  INFO 286042 --- [         task-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2020-09-09 09:36:38.019  WARN 286042 --- [  restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2020-09-09 09:36:38.022  INFO 286042 --- [onPool-worker-3] c.v.f.s.c.g.OpenApiSpecGenerator         : There are no connect endpoints to generate.
2020-09-09 09:36:38.028  INFO 286042 --- [onPool-worker-3] c.v.f.s.frontend.TaskUpdatePackages      : Skipping `pnpm install` because the frontend packages are already installed in the folder '/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/node_modules' and the hash in the file '/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
2020-09-09 09:36:38.028  INFO 286042 --- [onPool-worker-3] c.v.f.s.frontend.TaskCopyFrontendFiles   : Copying frontend resources from jar files ...
2020-09-09 09:36:38.083  INFO 286042 --- [         task-1] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2020-09-09 09:36:38.084  INFO 286042 --- [         task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-09-09 09:36:38.126  INFO 286042 --- [onPool-worker-3] c.v.f.s.frontend.TaskCopyFrontendFiles   : Visited 15 resources. Took 97 ms.
2020-09-09 09:36:38.172  INFO 286042 --- [onPool-worker-3] c.v.f.server.frontend.TaskUpdateImports  : Updated /home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/frontend/generated-flow-imports.js
2020-09-09 09:36:38.173  INFO 286042 --- [onPool-worker-3] c.v.f.server.frontend.TaskUpdateImports  : No js modules to update '/home/stefan/programmierung/java/vaadin/my-vaadin17-test2/target/frontend/generated-flow-imports.d.ts' file
2020-09-09 09:36:38.193  INFO 286042 --- [         task-2] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2020-09-09 09:36:38.432  INFO 286042 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-09-09 09:36:38.433  INFO 286042 --- [  restartedMain] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…
2020-09-09 09:36:38.528  INFO 286042 --- [  restartedMain] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
2020-09-09 09:36:38.539  INFO 286042 --- [  restartedMain] iat.vaadin17.Application                 : Started Application in 9.13 seconds (JVM running for 94.552)
2020-09-09 09:36:38.551  INFO 286042 --- [  restartedMain] i.vaadin17.data.generator.DataGenerator  : Generating demo data
2020-09-09 09:36:38.551  INFO 286042 --- [  restartedMain] i.vaadin17.data.generator.DataGenerator  : ... generating 100 Person entities...
2020-09-09 09:36:38.628  INFO 286042 --- [  restartedMain] i.vaadin17.data.generator.DataGenerator  : Generated demo data
2020-09-09 09:36:38.632  INFO 286042 --- [  restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 3ms
2020-09-09 09:36:38.783  INFO 286042 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-09-09 09:36:38.784  INFO 286042 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-09-09 09:36:38.787  INFO 286042 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
         Serving the 'stats.json' file dynamically.
ℹ ｢wdm｣: Hash: c8b008ba98fffaf738d2
Version: webpack 4.42.0
Time: 1277ms
Built at: 09.09.2020 09:36:39
     Asset      Size  Chunks             Chunk Names
index.html  1.08 KiB          [emitted]  
 + 7 hidden assets
Entrypoint bundle = build/vaadin-bundle-2475453a0a42cac69969.cache.js
Entrypoint export [big] = build/vaadin-export-b749fd7e0671df44d265.cache.js
Entrypoint devmodeGizmo = build/vaadin-devmodeGizmo-34b9ac7fd2fb8a44bcdc.cache.js
[../target/index.ts] 1.43 KiB {bundle} [built]
    + 567 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/.pnpm/registry.npmjs.org/html-webpack-plugin/3.2.0_webpack@4.42.0/node_modules/html-webpack-plugin/lib/loader.js!../target/index.html] 1.13 KiB {1} [built]
2020-09-09 09:36:39.407  INFO 286042 --- [onPool-worker-3] com.vaadin.flow.server.DevModeHandler    : Reusing webpack-dev-server running at http://localhost:35185
        + 3 hidden modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

ℹ ｢wdm｣: Compiling...
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 2ms
         Serving the 'stats.json' file dynamically.
ℹ ｢wdm｣: Hash: 0efc725c609d2000e772
Version: webpack 4.42.0
Time: 1342ms
Built at: 09.09.2020 09:36:40
                                            Asset      Size  Chunks                                Chunk Names
     build/vaadin-1-6a852c01ccdd71133e3c.cache.js   346 KiB       1  [emitted] [immutable]         
build/vaadin-bundle-07cec2f4198b047008b3.cache.js   285 KiB  bundle  [emitted] [immutable]         bundle
build/vaadin-export-92ee194f2a7ab09558a8.cache.js  16.6 MiB  export  [emitted] [immutable]  [big]  export
                                       index.html  1.08 KiB          [emitted]                     
 + 4 hidden assets
Entrypoint bundle = build/vaadin-bundle-07cec2f4198b047008b3.cache.js
Entrypoint export [big] = build/vaadin-export-92ee194f2a7ab09558a8.cache.js
Entrypoint devmodeGizmo = build/vaadin-devmodeGizmo-34b9ac7fd2fb8a44bcdc.cache.js
[../target/frontend/generated-flow-imports.js] 5.87 KiB {export} {1} [built]
    + 566 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
ℹ ｢wdm｣: Compiled successfully.

----------------- Frontend compiled successfully. -----------------

2020-09-09 09:36:42.029  INFO 286042 --- [nio-8080-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2020-09-09 09:53:38.086  WARN 286042 --- [alina-utility-1] com.vaadin.flow.server.VaadinSession     : A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
2020-09-09 10:06:38.182  WARN 286042 --- [alina-utility-2] com.vaadin.flow.server.VaadinSession     : A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
```

If I restart `mvn spring-boot:run` the app works fine.  However, I don't want to restart the whole application server for a simple change.  What do I have to adjust to make this working?
The guide https://vaadin.com/docs/v17/flow/getting-started/getting-started-intellij.html looks a bit like outdated, since it mentions jetty:run to start the application?

**Comment by joheriks** [comment]
@xylo There is a known timing-related problem with Vaadin and Spring Boot Devtools: the server restarts when IntelliJ deletes a class file during recompile but doesn't wait for the new class file, causing the route to be lost. Increasing the quiet time as described [here](https://vaadin.com/docs/v17/flow/workflow/setup-live-reload-springboot.html#a-id-configuration-a-additional-configuration) can help.

**Comment by xylo** [comment]
@joheriks Thanks a lot! Didn't see that the problem is actually mentioned in the doc. Nice!
